#program to guess a number similar to one generated by the computer
import random

number_to_Guess = random.randint(1, 100)
attempts = 0
while True:
  try:
  

   guess= int(input("Enter a number between 1 and 100: "))
   attempts += 1
   if guess>number_to_Guess:
  
    print("Too high!")
   elif guess<number_to_Guess:
    print("Too low!")
   else:
    print("Congraturations you got it in ", attempts, " attempts")
    break   
  except ValueError:
   print("Please enter a valid number")  